// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type NotificationsLog struct {
	ID             int64                 `json:"id"`
	NotificationID uuid.UUID             `json:"notification_id"`
	Payload        pqtype.NullRawMessage `json:"payload"`
	Status         string                `json:"status"`
	Attempts       sql.NullInt32         `json:"attempts"`
	ErrorText      sql.NullString        `json:"error_text"`
	CreatedAt      sql.NullTime          `json:"created_at"`
	UpdatedAt      sql.NullTime          `json:"updated_at"`
}
