// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications_log.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO notifications_log(notification_id, payload, status, attempts, error_text)
VALUES($1, $2, $3, $4, $5)
`

type InsertNotificationParams struct {
	NotificationID uuid.UUID             `json:"notification_id"`
	Payload        pqtype.NullRawMessage `json:"payload"`
	Status         string                `json:"status"`
	Attempts       sql.NullInt32         `json:"attempts"`
	ErrorText      sql.NullString        `json:"error_text"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.ExecContext(ctx, insertNotification,
		arg.NotificationID,
		arg.Payload,
		arg.Status,
		arg.Attempts,
		arg.ErrorText,
	)
	return err
}
